server:
  port: 3000
  mode: debug

database:
  # user:password@tcp(host:port)/dbname?charset=utf8mb4&parseTime=True&loc=Local
  dsn: "root:123456@tcp(127.0.0.1:3306)/smart?charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "smart_butler_secret_key"
  expire: 2592000 # 30d

# 登录接口白名单
auth:
  public_paths:
    - "/api/auth/login"
    - "/api/ping"
    - "/favicon.ico"

# 登录后权限排除的接口
permission:
  exclude_paths:
    - "/api/auth/logout"
